# Generated by Django 2.2.5 on 2019-11-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('regno', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('appart_no', models.IntegerField()),
                ('roadno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('costpersqyard', models.IntegerField()),
                ('otherexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facing', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='appartment/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mailid', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=30)),
                ('doj', models.DateField()),
                ('role', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='employee/')),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('regno', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('plotno', models.IntegerField()),
                ('roadno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('costpersqyard', models.IntegerField()),
                ('otherexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boundary', models.IntegerField()),
                ('facing', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='plots/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_no', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
